Script for uploading files improvement

diff --git a/src/test/resources/files_to_upload/multiple_upload_curl b/src/test/resources/files_to_upload/multiple_upload_curl
--- a/src/test/resources/files_to_upload/multiple_upload_curl
+++ b/src/test/resources/files_to_upload/multiple_upload_curl
@@ -1,16 +1,47 @@
 #!/bin/bash
+#
+# Copyright (c) 2016 Intel Corporation
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#    http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
 
-dir_files=(*.*)
-echo "Please provide name of the organization"
-read org
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --org=*)
+      org="${1#*=}"
+      ;;
+    --dir=*)
+      dir="${1#*=}"
+      ;;
+    --domain=*)
+      domain="${1#*=}"
+      ;;
+    *)
+      printf "Error: Invalid argument.\n"
+      exit 1
+  esac
+  shift
+done
+
+dir_files=(` ls $dir -p | grep -v / `)
 
 files=""
 for ((i=0;i<${#dir_files[@]} ;i++)); do
     files+="-F upload=@${dir_files[i]} "
 done
 
-if [ "$1" != "" ]; then
-	curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://hdfs-uploader.$1/rest/v1/files/`cf org $org --guid` | jq .;
+if [ "$domain" != "" ]; then
+	curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://hdfs-uploader.$domain/rest/v1/files/`cf org $org --guid` | jq .;
 else 
 	curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://localhost:8080/rest/v1/files/`cf org $org --guid` | jq .;
 fi
