DPNG-9325-extend documentation

diff --git a/src/test/resources/upload_scripts/multiple_upload_curl b/src/test/resources/upload_scripts/multiple_upload_curl
--- a/src/test/resources/upload_scripts/multiple_upload_curl
+++ b/src/test/resources/upload_scripts/multiple_upload_curl
@@ -26,6 +26,9 @@ while [ $# -gt 0 ]; do
     --domain=*)
       domain="${1#*=}"
       ;;
+    --port=*)
+      port="${1#*=}"
+      ;;
     *)
       printf "Error: Invalid argument.\n"
       exit 1
@@ -33,15 +36,25 @@ while [ $# -gt 0 ]; do
   shift
 done
 
+if [[ -f "$dir" ]]
+then
+  printf "Error: The path parameter specifies a file path, not a directory path.\n"
+  exit 1
+fi
+
 dir_files=(` ls $dir -p | grep -v / `)
 
 files=""
 for ((i=0;i<${#dir_files[@]} ;i++)); do
-    files+="-F upload=@${dir_files[i]} "
+    files+="-F upload=@$dir/${dir_files[i]} "
 done
 
 if [ "$domain" != "" ]; then
-	curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://hdfs-uploader.$domain/rest/v1/files/`cf org $org --guid` | jq .;
-else 
-	curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://localhost:8080/rest/v1/files/`cf org $org --guid` | jq .;
+	curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://hdfs-uploader.$domain/rest/v1/files/`cf org $org --guid`;
+else
+    if [ "$port" != "" ]; then
+	    curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://localhost:$port/rest/v1/files/`cf org $org --guid`;
+	else
+	    curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://localhost:8080/rest/v1/files/`cf org $org --guid`;
+	fi
 fi
diff --git a/src/test/resources/upload_scripts/upload_curl b/src/test/resources/upload_scripts/upload_curl
--- a/src/test/resources/upload_scripts/upload_curl
+++ b/src/test/resources/upload_scripts/upload_curl
@@ -26,6 +26,9 @@ while [ $# -gt 0 ]; do
     --domain=*)
       domain="${1#*=}"
       ;;
+    --port=*)
+      port="${1#*=}"
+      ;;
     *)
       printf "Error: Invalid argument.\n"
       exit 1
@@ -33,8 +36,18 @@ while [ $# -gt 0 ]; do
   shift
 done
 
+if [[ -d "$file" ]]
+then
+  printf "Error: The path parameter specifies a directory path, not a file path.\n"
+  exit 1
+fi
+
 if [ "$domain" != "" ]; then
-	curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data -F upload=@$file http://hdfs-uploader.$domain/rest/v1/files/`cf org $org --guid` | jq .;
+	curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data -F upload=@$file http://hdfs-uploader.$domain/rest/v1/files/`cf org $org --guid`;
 else
-	curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data -F upload=@$file http://localhost:8080/rest/v1/files/`cf org $org --guid` | jq .;
+    if [ "$port" != "" ]; then
+	    curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data -F upload=@$file http://localhost:$port/rest/v1/files/`cf org $org --guid`;
+	else
+	    curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data -F upload=@$file http://localhost:8080/rest/v1/files/`cf org $org --guid`;
+    fi
 fi
